sudo: false

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - inkscape
        - doxygen
        - gcc-4.8
        - g++-4.8
        - gcc-5
        - g++-5

cache:
    directories:
        - sconsCache

before_install:
    - export DISPLAY=:99.0
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi

install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install scons; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install doxygen; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew cask install inkscape; fi
    - python ./config/travis/installDependencies.py
    - ./config/travis/installDelight.sh
    - export DELIGHT=`pwd`/3delight
    - export LD_LIBRARY_PATH=$DELIGHT/lib:$LD_LIBRARY_PATH
    - export DL_SHADERS_PATH=$DELIGHT/shaders
    - export DL_DISPLAYS_PATH=$DELIGHT/displays
    - export PATH=$DELIGHT/bin:$PATH
    - if [ -n "$COMPILER_VERSION" ]; then export CXX="${CXX}-${COMPILER_VERSION}"; fi

script:
    - scons -j 2 install CXX=$CXX CXXSTD=$CXXSTD DEBUG=$DEBUG ENV_VARS_TO_IMPORT=PATH RMAN_ROOT=$DELIGHT BUILD_CACHEDIR=sconsCache
    # Preload libSegFault when running tests, so we get stack
    # traces from any crashes.
    - export LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - source ./config/travis/runGafferTest GafferTest
    - source ./config/travis/runGafferTest GafferUITest
    - source ./config/travis/runGafferTest GafferDispatchTest
    - source ./config/travis/runGafferTest GafferDispatchUITest
    - source ./config/travis/runGafferTest GafferCortexTest
    - source ./config/travis/runGafferTest GafferCortexUITest
    - source ./config/travis/runGafferTest GafferImageTest
    - source ./config/travis/runGafferTest GafferImageUITest
    - source ./config/travis/runGafferTest GafferSceneTest
    - source ./config/travis/runGafferTest GafferSceneUITest
    - source ./config/travis/runGafferTest GafferOSLTest
    - source ./config/travis/runGafferTest GafferOSLUITest
    - source ./config/travis/runGafferTest GafferRenderManTest
    - source ./config/travis/runGafferTest GafferRenderManUITest
    - source ./config/travis/runGafferTest GafferAppleseedTest
    - source ./config/travis/runGafferTest GafferAppleseedUITest
    - ./config/travis/printTestResults

before_cache:
    # This is run just before uploading the cache for next time.
    # SCons caches grow without bound so we want to remove old
    # files to prevent our caches becoming too big.
    - python ./config/travis/limitCacheSize.py
    - du -sh sconsCache

# Default values for environment variables we use to
# control the build.
env:
    - COMPILER_VERSION= CXXSTD=c++98 DEBUG=0

matrix:
    # Explicit list of additional permutations of environment
    # and compiler we want to test. These are on top
    # of the defaults provided by the compiler and
    # env setup above.
    include:
        - os: linux
          compiler: gcc
          env: COMPILER_VERSION= CXXSTD=c++98 DEBUG=1
        - os: linux
          compiler: gcc
          env: COMPILER_VERSION=4.8 CXXSTD=c++98 DEBUG=0
        - os: linux
          compiler: gcc
          env: COMPILER_VERSION=4.8 CXXSTD=c++11 DEBUG=0
        - os: linux
          compiler: gcc
          env: COMPILER_VERSION=5 CXXSTD=c++11 DEBUG=0
    exclude:
        - os: osx
          compiler: gcc
