# Standard build + test job

parameters:
  name: ''
  vmImage: ''
  container: ''
  buildType: 'RELEASE'
  threads: 2
  publish: false

jobs:

 - job: ${{ parameters.name }}_${{ parameters.buildType }}

   # We're seeing jobs take about an hour sometimes!
   timeoutInMinutes: 100

   ${{ if ne(parameters.container, '') }}:
      container: ${{ parameters.container }}

   pool:
     vmImage: ${{ parameters.vmImage }}

   variables:
     ARNOLD_ROOT: $(System.DefaultWorkingDirectory)/arnoldRoot
     DELIGHT: $(System.DefaultWorkingDirectory)/3delight
     BUILD_TYPE: ${{ parameters.buildType }}

   steps:

   - script: |
       brew update &&
       brew cask install xquartz https://raw.githubusercontent.com/Homebrew/homebrew-cask/5eafe6e9877c5524100b9ac1c5375fe8a2d039be/Casks/inkscape.rb &&
       sudo pip install scons==3.1.2 &&
       pip install sphinx==1.8.1 sphinx_rtd_theme==0.4.3 recommonmark==0.5.0 docutils==0.12
     displayName: 'Install Toolchain (Darwin)'
     condition: eq( variables['Agent.OS'], 'Darwin' )

   - script: |
        python --version
        # Pre-installs some floating dependencies of the main modules that no longer support 2.x
        pip install --user cryptography==2.9 &&
        pip install --user azure-common==1.1.23 azure-nspkg==3.0.2 azure-storage-blob==2.1.0 azure-storage-common==2.1.0 azure-storage-nspkg==3.1.0 PyGithub==1.45
        # Works around issues with earlier Python versions, remove once the Docker image is updated
        pip install --user sphinx==1.8.1
     displayName: 'Install Python Modules'

   - script: |
       sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off &&
       defaults -currentHost write ~/Library/Preferences/ByHost/com.apple.notificationcenterui doNotDisturb -boolean true &&
       sudo killall NotificationCenter &&
       defaults write com.apple.Dock autohide -bool true && sleep 1 && killall Dock
     displayName: 'Configure Environment (Darwin)'
     condition: eq( variables['Agent.OS'], 'Darwin' )

   # Provides $(Gaffer.*) variables
   - script: |
       ./config/azure/setBuildVars.py
       echo "##vso[task.setvariable variable=Gaffer.Sphinx]"`which sphinx-build`
     displayName: 'Set Custom Variables'
     env:
       GITHUB_ACCESS_TOKEN: $(githubAccessToken)

   # Docs builds regularly hang on mac, temporarily disable them for non-release build
   - script: |
       echo "##vso[task.setvariable variable=Gaffer.Sphinx]thisDoesNotExist"
     displayName: 'Disable Docs build (Darwin, non-release)'
     condition: and( succeeded(), and( eq( variables['Gaffer.GitHub.ReleaseID'], '' ), eq( variables['Agent.OS'], 'Darwin' ) ) )

   - script: |
       ./config/installDelight.sh &&
       ./config/installArnold.sh &&
       ./config/installDependencies.sh ./build
     displayName: 'Install Dependencies'
     env:
       ARNOLD_LOGIN: $(arnoldLogin)
       ARNOLD_PASSWORD: $(arnoldPassword)
       AZURE: 1

   - script: |
       Xvfb :99 -screen 0 1280x1024x24 &
       metacity&
     displayName: 'Start X (Linux)'
     condition: and( succeeded(), eq( variables['Agent.OS'], 'Linux' ) )
     env:
       DISPLAY: :99.0

   - script: |
       echo BUILD_TYPE=${{ parameters.buildType }}
       g++ --version
       scons -j ${{ parameters.threads }} build ENV_VARS_TO_IMPORT=PATH BUILD_TYPE=${{ parameters.buildType }} DELIGHT_ROOT=$DELIGHT ARNOLD_ROOT=$ARNOLD_ROOT BUILD_DIR=./build INSTALL_DIR=./install/$(Gaffer.Build.Name) BUILD_CACHEDIR=sconsCache SPHINX=$(Gaffer.Sphinx)
     displayName: 'Build'
     env:
       DISPLAY: :99.0
       AZURE: 1

   - script: |
       ./build/bin/gaffer test -stopOnFailure
     displayName: 'Test'
     env:
       DISPLAY: :99.0
       AZURE: 1
       USER: azureTestUser # ImageWriterTest requires $USER but by default Azure doesn't provide it
       ARNOLD_LICENSE_ORDER: none # Don't waste time looking for a license that doesn't exist

   - script: |
       scons -j ${{ parameters.threads }} package ENV_VARS_TO_IMPORT=PATH BUILD_TYPE=${{ parameters.buildType }} DELIGHT_ROOT=$DELIGHT ARNOLD_ROOT=$ARNOLD_ROOT BUILD_DIR=./build INSTALL_DIR=./install/$(Gaffer.Build.Name) BUILD_CACHEDIR=sconsCache SPHINX=$(Gaffer.Sphinx)
     displayName: 'Build (Docs + Package)'
     env:
       DISPLAY: :99.0
       AZURE: 1

   - script: |
       ./config/validateRelease.py --archive ./install/$(Gaffer.Build.Name).tar.gz
     displayName: 'Validate'
     condition: and( succeeded(), not( and( eq( variables['Gaffer.GitHub.ReleaseID'], '' ), eq( variables['Agent.OS'], 'Darwin' ) ) ) )

   - ${{ if eq(parameters.publish, true) }}:

     - script: |
         ./config/azure/publishBuild.py --archive ./install/$(Gaffer.Build.Name).tar.gz --repo $(Build.Repository.Name) --commit $(Gaffer.Source.Commit)
       displayName: "Publish Build"
       condition: and( succeeded(), or( eq( variables['Build.Reason'], 'PullRequest' ), eq( variables['Build.Reason'], 'Schedule' ) ) )
       env:
         GITHUB_ACCESS_TOKEN: $(githubAccessToken)
         AZURE_ACCESS_TOKEN: $(azureBlobAccessToken)

     - script: |
         ./config/publishRelease.py --archive ./install/$(Gaffer.Build.Name).tar.gz --repo $(Build.Repository.Name) --releaseId $(Gaffer.GitHub.ReleaseID)
       displayName: "Publish Release"
       condition: and( succeeded(), ne( variables['Gaffer.GitHub.ReleaseID'], '' ) )
       env:
         GITHUB_ACCESS_TOKEN: $(githubAccessToken)

